services:
  - type: web
    name: kchat
    env: node
    region: oregon
    plan: free
    buildCommand: |
      npm ci &&
      mkdir -p dist &&
      npx vite build &&
      npx esbuild server/index.ts --bundle --platform=node --target=node20 --format=esm --outfile=dist/index.js --packages=external &&
      ls -la dist/
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
    healthCheckPath: /api/health
    healthCheckTimeout: 100
    autoDeploy: true